services:
  - type: web
    name: slic-index
    runtime: static
    buildCommand: npm ci && npx tsc && npx vite build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
