import BrandLockup from "./BrandLockup";
import { collaborationLogos } from "./brandAssets";
import { getCopy } from "./siteCopy";
import type { Locale, SitePath } from "./types";

const footerEndnoteCopy: Record<
  Locale,
  {
    eyebrow: string;
    reuseLabel: string;
    reuseBody: string;
    creditLabel: string;
    creditBody: string;
    aiLabel: string;
    aiBody: string;
    liveLabel: string;
    liveBody: string;
  }
> = {
  en: {
    eyebrow: "Publication protocol",
    reuseLabel: "Reuse and credit",
    reuseBody:
      "SLIC is intended for public citation, teaching, replication, and critique. Keep the source visible, preserve the declared methodology, and do not imply paid placement or endorsement.",
    creditLabel: "Suggested credit",
    creditBody:
      "Non Arkara and Associate Professor Poon Thiengburanathum, Smart and Liveable Cities Index (SLIC), public ranking model, accessed [date], plus the deployment URL used.",
    aiLabel: "Algorithmic and AI disclosure",
    aiBody:
      "The public ordering is generated by the declared SLIC model rather than hand-ranked city by city. The doctrine, formula, and system architecture were co-developed by the two SLIC co-founders through multi-model AI research and coding workflows, including GPT-5-class, Claude Opus-class, Gemini planning workflows, and supporting agentic coding systems.",
    liveLabel: "Continuous model",
    liveBody:
      "This is designed as a live public ranking surface. As connected feeds, source checks, and monitored signals update, the board can move under the same declared logic.",
  },
  th: {
    eyebrow: "ข้อกำหนดการเผยแพร่",
    reuseLabel: "การนำไปใช้และการให้เครดิต",
    reuseBody:
      "SLIC ตั้งใจให้ถูกอ้างถึง ใช้ในการเรียน ทำซ้ำ และวิจารณ์ได้ในที่สาธารณะ เพียงต้องคงแหล่งที่มาและระเบียบวิธีไว้ชัดเจน และห้ามสื่อว่ามีการซื้ออันดับหรือได้รับการรับรองเป็นพิเศษ",
    creditLabel: "รูปแบบเครดิตที่แนะนำ",
    creditBody:
      "Non Arkara และ Associate Professor Poon Thiengburanathum, Smart and Liveable Cities Index (SLIC), public ranking model, accessed [วันที่], พร้อม URL ของหน้าที่ใช้งานจริง",
    aiLabel: "คำชี้แจงเรื่องอัลกอริทึมและ AI",
    aiBody:
      "ลำดับสาธารณะเกิดจากโมเดล SLIC ที่ประกาศไว้ ไม่ได้ถูกจัดอันดับด้วยมือทีละเมือง หลักคิด สูตร และสถาปัตยกรรมของระบบถูกพัฒนาร่วมโดยผู้ร่วมก่อตั้ง SLIC ทั้งสอง ผ่าน workflow วิจัยและเขียนโค้ดด้วย AI หลายตระกูล เช่น GPT-5-class, Claude Opus-class, Gemini planning workflows และระบบ agentic coding อื่น ๆ",
    liveLabel: "โมเดลต่อเนื่อง",
    liveBody:
      "นี่คือพื้นผิวการจัดอันดับแบบสาธารณะสด เมื่อ feed ที่เชื่อมอยู่ การตรวจแหล่งข้อมูล และสัญญาณที่เฝ้าดูเปลี่ยน บอร์ดก็สามารถขยับได้ภายใต้ตรรกะเดียวกันที่ประกาศไว้",
  },
  zh: {
    eyebrow: "发布协议",
    reuseLabel: "复用与署名",
    reuseBody:
      "SLIC 本来就允许公开引用、教学使用、复现与批评。只要保留来源、说明方法，并且不要暗示任何付费上榜或额外背书。",
    creditLabel: "建议署名",
    creditBody:
      "Non Arkara 与 Associate Professor Poon Thiengburanathum, Smart and Liveable Cities Index (SLIC), public ranking model, accessed [访问日期]，并附上所使用页面的部署 URL。",
    aiLabel: "算法与 AI 披露",
    aiBody:
      "公开顺位由已声明的 SLIC 模型生成，而不是人工逐城手排。这套方法论、公式与系统架构由两位 SLIC 共同创始人通过多模型 AI 研究与编码工作流共同开发，涉及 GPT-5-class、Claude Opus-class、Gemini planning workflows 与其他 agentic coding 系统。",
    liveLabel: "持续模型",
    liveBody:
      "这是一套面向公开的实时排名界面。随着接入数据流、来源校验与被监测信号更新，榜单会在同一套已声明逻辑下发生变化。",
  },
};

function navigateLink(
  event: React.MouseEvent<HTMLAnchorElement>,
  onNavigate: (path: SitePath) => void,
  path: SitePath,
) {
  event.preventDefault();
  onNavigate(path);
}

export default function SiteFooter({
  onNavigate,
  locale,
}: {
  onNavigate: (path: SitePath) => void;
  locale: Locale;
}) {
  const copy = getCopy(locale);
  const endnotes = footerEndnoteCopy[locale];

  return (
    <footer className="site-footer section">
      <div className="site-footer-grid">
        <div className="site-footer-brand">
          <BrandLockup eyebrow={copy.footer.eyebrow} microCopy={copy.footer.title} />
          <p className="site-footer-summary">{copy.footer.summary}</p>
        </div>

        <article className="site-footer-card">
          <p className="panel-label">{copy.footer.transparencyLabel}</p>
          <p>{copy.footer.disclosure}</p>
          <p>{copy.footer.privacy}</p>
          <p>{copy.footer.coverage}</p>
        </article>

        <article className="site-footer-card">
          <p className="panel-label">{copy.footer.collaborationLabel}</p>
          <p>{copy.footer.collaboration}</p>
          <div className="partner-logo-strip" aria-label={copy.footer.collaborationLabel}>
            {collaborationLogos.map((logo) => (
              <div className="partner-logo-card" key={logo.name}>
                <img src={logo.src} alt={logo.alt} loading="lazy" />
              </div>
            ))}
          </div>
        </article>
      </div>

      <div className="site-footer-endnotes">
        <div className="section-heading compact-heading">
          <p className="eyebrow">{endnotes.eyebrow}</p>
        </div>
        <div className="site-footer-endnote-grid">
          <article className="site-footer-endnote">
            <p className="panel-label">{endnotes.reuseLabel}</p>
            <p>{endnotes.reuseBody}</p>
          </article>
          <article className="site-footer-endnote">
            <p className="panel-label">{endnotes.creditLabel}</p>
            <p>{endnotes.creditBody}</p>
          </article>
          <article className="site-footer-endnote">
            <p className="panel-label">{endnotes.aiLabel}</p>
            <p>{endnotes.aiBody}</p>
          </article>
          <article className="site-footer-endnote">
            <p className="panel-label">{endnotes.liveLabel}</p>
            <p>{endnotes.liveBody}</p>
          </article>
        </div>
      </div>

      <div className="site-footer-bottom">
        <nav className="topnav" aria-label="Site navigation">
          <a href="/" onClick={(event) => navigateLink(event, onNavigate, "/")}>
            {copy.nav.home}
          </a>
          <a href="/about-slic" onClick={(event) => navigateLink(event, onNavigate, "/about-slic")}>
            {copy.nav.aboutSlic}
          </a>
          <a href="/rankings" onClick={(event) => navigateLink(event, onNavigate, "/rankings")}>
            {copy.nav.rankings}
          </a>
          <a href="/methodology" onClick={(event) => navigateLink(event, onNavigate, "/methodology")}>
            {copy.nav.methodology}
          </a>
          <a href="/thailand" onClick={(event) => navigateLink(event, onNavigate, "/thailand")}>
            {copy.nav.thailand}
          </a>
          <a href="/ideas" onClick={(event) => navigateLink(event, onNavigate, "/ideas")}>
            {copy.nav.ideas}
          </a>
        </nav>
        <p className="site-footer-note">{copy.footer.note}</p>
      </div>
    </footer>
  );
}
